version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: sl_user
      MYSQL_PASSWORD: sl_password
      MYSQL_DATABASE: spaced_learning
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/index.js"
volumes:
  db_data: